Resize window, transport mouse, and more.
Stengo/DeskPad pull request #16
Opened 2023-10-26 23:07 UTC by EarlOrlando

This pull request addresses the following improvements:
- The visible window is now resizable so that it can occupy as much space as the user wants, regardless of the resolution of the virtual display. This is helpful to optimize the size of the window in the physical display. This feature addresses issues https://github.com/Stengo/DeskPad/issues/11 and https://github.com/Stengo/DeskPad/issues/2.
- DeskPad captures the clicks over the visible window, and when that happens, the coordinates are converted to the coordinates of the virtual display, and the cursor is moved. This feature addresses issues https://github.com/Stengo/DeskPad/issues/12 and https://github.com/Stengo/DeskPad/issues/13. This feature is configurable through a new checkbox in the menu.
- Added more standard display resolutions
- Issue https://github.com/Stengo/DeskPad/issues/6 is partially addressed. The lacking feature is to detect if the cursor is on the edge of the virtual cursor. In that case, we want to move the cursor to the display where the visible window is shown in the position corresponding to the edge of the window.

2023-10-26 23:13 UTC, EarlOrlando commented
@Stengo, please look at this pull request when you have time. Feel free to reach out if needed. Thanks in advance.

2023-10-28 09:01 UTC, Stengo requested changes
Thank you so much for your contribution! It's amazing to see people step in to improve the app 🙂 

Your implementation appears to work beautifully, so almost all of my comments are about architectural concerns.

I'm aware that Redux is still quite unusual in the Swift community, so contributing to DeskPad comes with a bit of a learning curve, but I truly believe it's the most sensible general-purpose architecture for application programming and I think learning it (or its derivates like [The Composable Architecture](https://github.com/pointfreeco/swift-composable-architecture)) is well worth the while and DeskPad is still small enough to easily be able to grasp the whole flow 🙂

2023-10-31 18:05 UTC, acrylicus commented on DeskPad/Frontend/Screen/ScreenViewController.swift
> +            view.window?.contentAspectRatio = NSSize(width: viewData.resolution.width, height: viewData.resolution.height)
Agree - the fuzziness is driving me crazy!!! An option to snap window size to resolution is required

2023-10-31 18:05 UTC, acrylicus commented
Amazing! Love your work:)

2023-10-31 19:39 UTC, EarlOrlando commented on DeskPad/Frontend/Screen/ScreenViewController.swift
> +            view.window?.contentAspectRatio = NSSize(width: viewData.resolution.width, height: viewData.resolution.height)
I'm working on the requested changes. This is my first interaction with Swift and Redux, which is not very straightforward, but I expect to have it ready soon. 

Regarding the fuzziness, it might depend on the monitor, but I have this issue only when the high resolution is selected and it works amazingly with low resolution (in display settings), even if the window size is not mapped 1:1 to the native resolution. Could you please check if it's fuzzy with both high and low resolutions?

2023-11-02 01:42 UTC, EarlOrlando commented on DeskPad/AppDelegate.swift
> +        UserDefaults.standard.set(sender.state == .on, forKey: "CheckboxState")
HI @Stengo! Thank you so much for your inputs. It took me a while to understand the Redux architecture, but I finally got it and implemented the requested changes. Please take a look and let me know your thoughts.

2023-11-02 01:43 UTC, EarlOrlando commented on DeskPad/Frontend/Screen/ScreenViewController.swift
> +        }
Done!

2023-11-02 01:45 UTC, EarlOrlando commented on DeskPad/Frontend/Screen/ScreenViewController.swift
> +            view.window?.contentAspectRatio = NSSize(width: viewData.resolution.width, height: viewData.resolution.height)
My proposed solution is as follows:
- Added a menu button to reset the window size to have a 1:1 size with the configured resolution.
- Added a menu button to enable/disable the ability to resize the window so that you can stick with the 1:1 size with the configured resolution without having to deal with unwanted resizes.

Please take a look at the updated code. It should be good enough to cover all use cases.

2023-11-02 01:45 UTC, EarlOrlando commented on DeskPad.xcodeproj/project.pbxproj
> +				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "-";
Done!

2023-11-05 10:19 UTC, Stengo requested changes
Once again thank you for the work you put in! 👏  I've added a few comments to point out some of the pitfalls when working with a Redux architecture, but ultimately I think a lot of this is not actually necessary for these features.

I've just sat down and reworked the implementation from first principles and ended up with a few assumptions that I think make both the code as well as the user experience easier:
- teleportation is a generally useful feature and I can't think of anyone who would want to disable it, so I don't think we need a menu item for it. We can however simplify the implementation.
- similarly, screen resizing should be useful to anyone, but I think snapping is a far more common and intuitive experience than a menu button

I pushed what I ended up with to the `earl-rework` branch (https://github.com/Stengo/DeskPad/compare/main...earl-rework), which I based off of main.
Of course I'd still like for you to get the credit since you did the bulk of the work, so if you'd like you could apply those changes to your branch 🙂 If you've got any feedback or concerns about my reimplementation definitely let me know and we can adjust it!

2023-11-05 10:19 UTC, Stengo commented on DeskPad/AppDelegate.swift
> +        }
Any access (read and write) to the user defaults should live in a side effect to ensure that there's a unified, testable interface that keeps any outside interference out of the core redux flow.

2023-11-05 10:19 UTC, Stengo commented on DeskPad/AppDelegate.swift
> +        }
This should also live in a side effect or the view layer itself, in this case the view can get the same information via a gesture recognizer 🙂

2023-11-05 10:19 UTC, Stengo commented on DeskPad/AppDelegate.swift
> +        store.dispatch(MouseLocationAction.setWindow(window: window))
Objects are never allowed to be stored in a redux state, as the entire architecture is based around pure functions without any side effect. Any access to this would have to work through a state observer or side effect!

2023-11-05 10:19 UTC, Stengo commented on DeskPad/AppDelegate.swift
> +            store.dispatch(MouseLocationEvent.localMouseMoved(mouseLocation: NSEvent.mouseLocation, event: $0))
This would lead to an incredibly noisy redux flow, as these are very high frequency changes that we don't actually need. Ideally we keep things like this local to a side effect unless multiple components within the app need access to it!

2023-11-05 10:19 UTC, Stengo commented on DeskPad/AppDelegate.swift
> +        return true
This is also not quite permissible in a Redux architecture, since there is a unified state that is responsible for keeping track of things!

2023-11-05 10:19 UTC, Stengo commented on DeskPad/Frontend/Screen/ScreenViewController.swift
> +            CGVirtualDisplayMode(width: 1920, height: 1015, refreshRate: 60),
Could you point out what the intent of these resolutions is? I'd like to avoid adding highly specific ones unless there is a broadly applicable use case 🙂

2023-11-06 21:58 UTC, EarlOrlando commented on DeskPad/Frontend/Screen/ScreenViewController.swift
> +            CGVirtualDisplayMode(width: 1920, height: 1015, refreshRate: 60),
The primary goal behind window resizing is to maximize the actual DeskPad window area when sharing the screen while maintaining a clear and sharp visual representation. I recognize the importance of preserving a 1:1 window-to-pixel mapping to avoid any visual distortion.

A straightforward (naive) approach to achieve this balance involves setting 16:9 resolutions but excluding the height of the DeskPad title bar and macOS menu bar.

Upon contemplation, I explored two alternative approaches that, due to the intricacies of Apple's AppKit and Swift, weren't immediately straightforward to implement, given my limited experience:

- **Menu Option for Custom Resolutions:** Implementing a menu item to enable users to create and remove custom resolutions.
- **Menu Option to Set Resolution Based on the Current Window Size:** Providing a menu option to create a new custom resolution aligned with the current window size.

Considering my typical usage scenario, which I believe is quite common, users typically work with up to two monitors with varying resolutions (one for work and one for home displays). They might need, at most, a couple of custom resolutions to optimize the display when screen sharing.

The intention behind these suggested approaches is to offer a user-friendly way to manage resolutions. I don't expect the user to add several custom resolutions.

2023-11-06 21:59 UTC, EarlOrlando commented on DeskPad/Frontend/Screen/ScreenViewController.swift
> +            CGVirtualDisplayMode(width: 1920, height: 1015, refreshRate: 60),
But it's ok, I can keep my custom resolutions in my fork :)

2023-11-06 22:28 UTC, EarlOrlando commented
I reset my branch to yours. You wrote the code so the credit is yours :) Feel free to approve and merge!

2023-11-11 08:38 UTC, Stengo approved these changes

2023-11-11 08:38 UTC, merged

2023-11-11 09:11 UTC, Stengo commented
Just released [v1.2](https://github.com/Stengo/DeskPad/releases/tag/v1.2) with all of these changes 🚀 
Once again, thank you so much for taking the initiative!